CREATE TABLE [dbo].[AnimalTags] (
    [Id]       UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    [AnimalId] UNIQUEIDENTIFIER NOT NULL,
    [Tag]      NVARCHAR(100)    NOT NULL,
    CONSTRAINT [PK_AnimalTags] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [FK_AnimalTags_Animals] FOREIGN KEY ([AnimalId]) REFERENCES [dbo].[Animals]([Id]) ON DELETE CASCADE
);
