CREATE TABLE [dbo].[Animals] (
    [Id]                 UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    [Slug]               NVARCHAR(300)    NOT NULL,
    [CommonName]         NVARCHAR(300)    NOT NULL,
    [ScientificName]     NVARCHAR(300)    NULL,
    [Summary]            NVARCHAR(MAX)    NOT NULL DEFAULT '',
    [Description]        NVARCHAR(MAX)    NOT NULL DEFAULT '',
    [CategoryId]         UNIQUEIDENTIFIER NOT NULL,
    [TaxonomyId]         UNIQUEIDENTIFIER NULL,
    [IsPet]              BIT              NOT NULL DEFAULT 0,
    [ImageUrl]           NVARCHAR(500)    NULL,
    [ConservationStatus] NVARCHAR(100)    NULL,
    [NativeRegion]       NVARCHAR(500)    NULL,
    [Habitat]            NVARCHAR(MAX)    NULL,
    [Diet]               NVARCHAR(MAX)    NULL,
    [Lifespan]           NVARCHAR(200)    NULL,
    [SizeInfo]           NVARCHAR(MAX)    NULL,
    [Behaviour]          NVARCHAR(MAX)    NULL,
    [FunFacts]           NVARCHAR(MAX)    NULL,
    [GeneratedAt]        DATETIME2        NULL,
    [ReviewedAt]         DATETIME2        NULL,
    [ReviewedBy]         NVARCHAR(200)    NULL,
    [IsPublished]        BIT              NOT NULL DEFAULT 0,
    [CreatedAt]          DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME(),
    [UpdatedAt]          DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME(),
    [GbifTaxonKey]       INT              NULL,
    [GbifCanonicalName]  NVARCHAR(300)    NULL,
    [MapTileUrlTemplate] NVARCHAR(2000)   NULL,
    [MapObservationCount] INT             NULL,
    [MapMinLat]          FLOAT            NULL,
    [MapMaxLat]          FLOAT            NULL,
    [MapMinLng]          FLOAT            NULL,
    [MapMaxLng]          FLOAT            NULL,
    [ImageLicense]       NVARCHAR(100)    NULL,
    [ImageRightsHolder]  NVARCHAR(500)    NULL,
    [ImageSource]        NVARCHAR(500)    NULL,
    [WikipediaUrl]       NVARCHAR(500)    NULL,
    [ConservationStatusCode] NVARCHAR(5)  NULL,
    [PopulationTrend]    NVARCHAR(20)     NULL,
    [PopulationEstimate] NVARCHAR(200)    NULL,
    [DietTypeCode]       NVARCHAR(50)     NULL,
    [ActivityPatternCode] NVARCHAR(50)    NULL,
    [DomesticationStatusCode] NVARCHAR(50) NULL,
    [WeightMinKg]        DECIMAL(10,2)    NULL,
    [WeightMaxKg]        DECIMAL(10,2)    NULL,
    [LengthMinCm]        DECIMAL(10,2)    NULL,
    [LengthMaxCm]        DECIMAL(10,2)    NULL,
    [SpeedMaxKph]        DECIMAL(10,2)    NULL,
    [LifespanWildMinYears] INT            NULL,
    [LifespanWildMaxYears] INT            NULL,
    [LifespanCaptivityMinYears] INT       NULL,
    [LifespanCaptivityMaxYears] INT       NULL,
    [GestationMinDays]   INT              NULL,
    [GestationMaxDays]   INT              NULL,
    [LitterSizeMin]      INT              NULL,
    [LitterSizeMax]      INT              NULL,
    [AlsoKnownAs]        NVARCHAR(500)    NULL,
    [DistinguishingFeatures] NVARCHAR(MAX) NULL,
    [LegalProtections]   NVARCHAR(MAX)    NULL,
    [NativeContinentsJson] NVARCHAR(500)  NULL,
    [NativeCountriesJson] NVARCHAR(MAX)   NULL,
    [ColoursJson]        NVARCHAR(500)    NULL,
    [HabitatTypesJson]   NVARCHAR(500)    NULL,
    [DataSourceVersion]  INT              NOT NULL DEFAULT 1,
    [LastDataFetchAt]    DATETIME2        NULL,
    [DeletedAt]          DATETIME2        NULL,
    [Version]            INT              NOT NULL DEFAULT 1,
    CONSTRAINT [PK_Animals] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [FK_Animals_Categories] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Categories]([Id]),
    CONSTRAINT [FK_Animals_Taxonomy] FOREIGN KEY ([TaxonomyId]) REFERENCES [dbo].[Taxonomy]([Id])
);
